---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
  namespace: sandbox
data:
  index.html: |
    <html>
    <body>
    <p>Hello world 2!</p>
    <body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-2
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        service: service-2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index-config
        configMap:
          name: nginx-config-2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-2
  namespace: sandbox
spec:
  selector:
    app: nginx
    service: service-2
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30082